### ISSUE TITLE
Strange Hitbox Bug After Bullet Jumping

### ISSUE THREAD

**Issue by pebleblebl** [Gronkins/Bullet_Bunny#10] opened 2023-05-08 09:50 UTC
## Version: 2023-04-02 - testing day build

**Description:**

After bullet jumping towards an enemy and remaining stationary, any subsequent attacks would phase through an enemy and not kill them. This would be fixed after moving slightly or jumping.
***
**Reproducing the bug + theory:**

Step 1: Dash towards an enemy horizontally and enter melee range. 
Step 2: Remain stationary and input the attack command.

After performing a dash and remaining stationary, Buck might be remaining in some sort of dash state which doesn't allow hitboxes to spawn?
***
**Potential Solution / Solution:**

Revert him back to original idle state after performing a dash and remaining stationary

***
**Operating System:**

Windows 10
***

**Comment by Gronkins** [comment] 2023-07-09 08:19
This issue was caused by the enemy's rigidbody entering a 'sleep mode' in order to save on performance. The issue was, the enemies were not waking up in time (presumably) due to the fast attack speed of the player.

This was resolved by adjusting the enemy's rigidbody collision detection to always be awake.

**Closed by Gronkins** 2023-07-09 08:19 UTC
